services:
  fastapi:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/code/app
    depends_on:
      - mysql
      - mongodb
      - redis
      - minio
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    shm_size: 1G
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass yourpassword --appendonly yes
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    command: ["--auth"]
    restart: always
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "13306:3306"
    
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=fastapi_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always