spring:
  config:
    activate:
      on-profile: storage
  # LOCAL STORAGE
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  storage:
    location: ${LOCAL_UPLOAD_PATH}    # 로컬 파일 저장 경로
    temp-dir: ${LOCAL_UPLOAD_TEMP_PATH}       # 임시 파일 저장 경로

  # MINIO STORAGE
  minio:
    endpoint: ${MINIO_ENDPOINT}
    bucket-name: ${MINIO_BUCKET_NAME}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    secure: false


