spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    group:
      prod:
        - db
        - auth
        - storage
        - fastapi
        - ai
    active: ${SPRING_PROFILES_ACTIVE}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      processing-data:
        name: train-requests
        partitions: 1
        replicas: 1
    properties:
      spring.json.trusted.packages: "*"
  management:
    endpoints:
      web:
        exposure:
          include: health,info
# 서버 포트 설정
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  baseUrl: ${BASE_URL}
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: 20000ms
    max-connections: 10000
    accept-count: 100
    keep-alive-timeout: 30s


logging:
  level:
    #    javax.management.remote.rmi: ERROR
    #    sun.rmi: ERROR
    #    jdk.internal.httpclient: ERROR
    root: INFO

# application.yml
firebase:
  config:
    path: classpath:firebase-service-account.json