spring:
  config:
    activate:
      on-profile: auth

  #OAUTH 설정
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
  #JWT 설정
  jwt:
    secret_key: ${SERVER_SECRET_KEY}
    access_expiration: 604800000
    refresh_expiration: 604800000